spring:
  application:
    name: codeSphere

  datasource:
    url: jdbc:mysql://localhost:3306/codesphere
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

server:
  port: 8082
