spring:
  application:
    name: codeSphere
  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    url: jdbc:mysql://localhost:3306/codesphere
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 8080

jwt:
  secretKey:

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static:
    s3:
      bucketAvatar:
      bucketSolution:
      bucketFeature:


judge0:
  api:
    apiUrl:
    apiKey:

#Hibernate properties

PAYOS:
  PAYOS_CLIENT_ID:
  PAYOS_API_KEY:
  PAYOS_CHECKSUM_KEY:


